export enum PromptsOrderBy {
    PROMPT_NAME_WITH_OWNER = 'PROMPT_NAME_WITH_OWNER',
    PROMPT_UPDATED_AT = 'PROMPT_UPDATED_AT',
    PROMPT_RECOMMENDED = 'PROMPT_RECOMMENDED',
    PROMPT_RELEVANCE = 'PROMPT_RELEVANCE',
}
